---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - klusterlet-config.yaml
patches:
  - path: add-hypershift-params.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: hypershift-aws-cluster
  - patch: |
      - op: replace
        path: /spec/template/spec/source/targetRevision
        value: 0.1.0
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: hypershift-aws-cluster
  - patch: |
      - op: replace
        path: /spec/channel
        value: stable-2.6
    target:
      group: operators.coreos.com
      kind: Subscription
      name: multicluster-engine
  - path: argocd-rbac.yaml
    target:
      group: argoproj.io
      kind: ArgoCD
