resources:
- https://github.com/amisstea/crossplane-control-plane/crossplane/ocp?ref=KFLUXVNGD-92-test
- https://github.com/amisstea/crossplane-control-plane/config/ocp?ref=KFLUXVNGD-92-test

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
