resources:
- https://github.com/amisstea/crossplane-control-plane/crossplane?ref=provider-kubernetes-in-cluster
- https://github.com/amisstea/crossplane-control-plane/config?ref=provider-kubernetes-in-cluster

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
