resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/amisstea/integration-service/config/default?ref=2dcb65a6ed08dc8b3ef47773b71382c2a4c76364
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/amisstea/integration-service
    newTag: latest
namespace: integration-service
patches:
  - ./manager_resources_patch.yaml
